[package]
name = "edgeware-rpc-debug"
version = '0.1.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
tokio = { version = "1.12.0", features = ["time", "sync"] }
futures = { version = "0.3", features = ["compat"] }
jsonrpc-core = "18.0.0"

ethereum = { version = "0.12", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.13.1", default-features = false, features = ["rlp", "codec"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }

edgeware-rpc-core-debug = { path = "../../rpc-core/debug" }
edgeware-rpc-core-types = { path = "../../rpc-core/types" }
edgeware-client-evm-tracing = { path = "../../evm-tracing" }
edgeware-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }
fc-consensus = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
fc-db = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
fc-rpc = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest", features = ["rpc_binary_search_estimate"] }
fp-rpc = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
