[workspace]
members = [
	"modules/edge-treasury-reward",
	"modules/chainbridge",
	"modules/edge-chainbridge",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc",
	"node/rpc-client",
	"node/runtime",
	"node/runtime-interface",
	"node/testing",
]
exclude = ["vendor"]

[profile.release]
# Edgeware runtime requires unwinding.
panic = "unwind"

[profile.dev.package]
aes-soft = { opt-level = 3 }
aesni = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crossbeam-queue = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
h2 = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

# Generated with: `cargo lock -s | grep substrate.git | cut -d' ' -f2 | awk '{print $0, "= { git = \"https://github.com/paritytech/substrate.git\", rev = \"00b41bcea913acad52e48de692cc615e7e2fc3e5\" }"}'`
# Make sure to have cargo-lock installed with: `cargo install cargo-lock --features=cli`

[patch.crates-io]
# frontier deps
pallet-evm = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
pallet-evm-precompile-simple = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
pallet-ethereum = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
fc-rpc = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
fc-consensus = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
fp-rpc = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
fp-consensus = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }
fc-rpc-core = { git = "https://github.com/hicommonwealth/frontier.git", rev = "c048b11f7eac80c543b5ea45a1f2da3f60c5fd5d" }

# substrate deps
fork-tree = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-executive = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-metadata = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-support = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-support-procedural = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-support-procedural-tools = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-support-procedural-tools-derive = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-system = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-authorship = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-contracts = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-contracts-proc-macro = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-democracy = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-identity = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-im-online = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-multisig = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-offences = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-proxy = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-recovery = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-session = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-utility = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
pallet-vesting = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-block-builder = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-chain-spec-derive = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-cli = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-cli-proc-macro = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-client-db = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-executor = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-executor-common = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-executor-wasmi = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-executor-wasmtime = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-informant = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-light = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-network = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-network-gossip = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-offchain = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-peerset = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-proposer-metrics = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-rpc-server = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-service = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-state-db = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-telemetry = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-tracing = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-transaction-graph = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-allocator = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-api = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-api-proc-macro = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-authorship = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-chain-spec = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-consensus-vrf = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-database = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-debug-derive = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-io = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-keystore = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-npos-elections-compact = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-panic-handler = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-sandbox = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-serializer = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-session = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-staking = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-std = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-storage = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-tasks = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-trie = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-utils = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-version = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
substrate-browser-utils = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
substrate-frame-cli = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
substrate-test-client = { git = "https://github.com/paritytech/substrate.git", rev = "00b41bcea913acad52e48de692cc615e7e2fc3e5" }
