[package]
name = "edgeware-primitives"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c", default-features = false }

[dev-dependencies]
sp-serializer = { git = "https://github.com/paritytech/substrate.git", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]