[package]
name = "edgeware-primitives"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
sp-core = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel", default-features = false }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel", default-features = false }

[dev-dependencies]
sp-serializer = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]