[package]
name = "edgeware-runtime"
version = "0.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"
build = "build.rs"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }
static_assertions = "1.1.0"
evm = { version = "0.19.0", default-features = false, features = ["with-codec"] }

# primitives
sp-application-crypto = { version = "2.0.0", default-features = false }
sp-authority-discovery = { version = "2.0.0", default-features = false }
sp-consensus-aura = { version = "0.8.0", default-features = false }
sp-block-builder = { version = "2.0.0", default-features = false}
sp-inherents = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-api = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-staking = { version = "2.0.0", default-features = false }
sp-keyring = { version = "2.0.0", optional = true }
sp-session = { version = "2.0.0", default-features = false }
sp-transaction-pool = { version = "2.0.0", default-features = false }
sp-version = { version = "2.0.0", default-features = false }
sp-offchain = { version = "2.0.0", default-features = false }

# edgeware primitives
edgeware-primitives = { path = "../primitives", default-features = false }

# pallet dependencies
# pallet-assets = { version = "2.0.0", default-features = false }
pallet-authority-discovery = { version = "2.0.0", default-features = false }
pallet-authorship = { version = "2.0.0", default-features = false }
pallet-aura = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-collective = { version = "2.0.0", default-features = false, features = ["runtime-benchmarks"] }
pallet-contracts = { default-features = false, version = "2.0.0" }
pallet-contracts-primitives = { default-features = false, version = "2.0.0" }
pallet-contracts-rpc-runtime-api = { default-features = false, version = "0.8.0" }
pallet-democracy = { version = "2.0.0", default-features = false }
pallet-elections-phragmen = { version = "2.0.0", default-features = false }
frame-executive = { version = "2.0.0", default-features = false }
pallet-grandpa = { version = "2.0.0", default-features = false }
pallet-identity = { version = "2.0.0", default-features = false }
pallet-im-online = { version = "2.0.0", default-features = false }
pallet-indices = { version = "2.0.0", default-features = false }
pallet-multisig = { version = "2.0.0", default-features = false }
pallet-offences = { version = "2.0.0", default-features = false }
pallet-proxy = { version = "2.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false }
pallet-recovery = { version = "2.0.0", default-features = false }
pallet-scheduler = { version = "2.0.0", default-features = false }
pallet-session = { version = "2.0.0", default-features = false, features = ["historical"] }
pallet-staking = { version = "2.0.0", default-features = false }
pallet-staking-reward-curve = { version = "2.0.0" }
pallet-sudo = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false }
pallet-timestamp = { version = "2.0.0", default-features = false }
pallet-treasury = { version = "2.0.0", default-features = false }
pallet-utility = { version = "2.0.0", default-features = false }
pallet-transaction-payment = { version = "2.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0", default-features = false }
pallet-vesting = { version = "2.0.0", default-features = false }

# pallet-bounties = { git = "https://github.com/paritytech/substrate.git", rev = "987a9723920217917f2708388d150add5ef52ef7", default-features = false }
# pallet-tips = { git = "https://github.com/paritytech/substrate.git", rev = "987a9723920217917f2708388d150add5ef52ef7", default-features = false }

signaling = { package = "edge-signaling", path = "../../modules/edge-signaling", default-features = false }
treasury-reward = { package = "edge-treasury-reward", path = "../../modules/edge-treasury-reward", default-features = false }
voting = { package = "edge-voting", path = "../../modules/edge-voting", default-features = false }

edge-chainbridge = { path = "../../modules/edge-chainbridge", default-features = false }
chainbridge = { path = "../../modules/chainbridge", default-features = false }

pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "v0.4-hotfixes" }
fp-rpc = { default-features = false, git = "https://github.com/purestake/frontier", branch = "v0.4-hotfixes" }
pallet-ethereum = { default-features = false, git = "https://github.com/purestake/frontier", branch = "v0.4-hotfixes" }

# Cumulus depedencies for Rococo
cumulus-runtime = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-message-broker = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }

# used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-system-benchmarking = { version = "2.0.0", default-features = false, optional = true }
hex-literal = { version = "0.3.1", optional = true }

[build-dependencies]
substrate-wasm-builder = { package = "substrate-wasm-builder", version = "3.0.0" }

[dev-dependencies]
sp-io = { version = "2.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"sp-keyring",
	"sp-session/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sp-offchain/std",

	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",

#	"pallet-assets/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-multisig/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"pallet-randomness-collective-flip/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-scheduler/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",

# 	"pallet-bounties/std",
#	"pallet-tips/std",

	"pallet-utility/std",
	"pallet-vesting/std",

	"fp-rpc/std",
	"pallet-ethereum/std",
	"evm/std",

	"edgeware-primitives/std",
	"signaling/std",
	"treasury-reward/std",
	"voting/std",
	"edge-chainbridge/std",
	"chainbridge/std",

    "parachain-info/std",
    "cumulus-runtime/std",
    "cumulus-message-broker/std",
    "cumulus-parachain-upgrade/std",
]

runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-system-benchmarking",
	"hex-literal",
	"signaling/runtime-benchmarks",
	"voting/runtime-benchmarks",
	"chainbridge/runtime-benchmarks",
]
