[package]
name = "evm-tracing-events"
version = '0.1.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
environmental = { version = "1.1.3", features=["std"], default-features = false }

codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["full"] }
ethereum = { version = "0.11.1", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.12.1", default-features = false, features = ["codec"] }

evm = { version = "0.33.0", default-features = false, features = ["with-codec"] }
evm-runtime = { version = "0.33.0", default-features = false }
evm-gasometer = { version = "0.33.0", default-features = false }
sp-runtime-interface = { version = "6.0.0", default-features = false }


[features]
default = ["std"]
evm-tracing = ["evm/tracing", "evm-runtime/tracing", "evm-gasometer/tracing"]
std = [
	"codec/std",
	"environmental/std",
	"ethereum/std",
	"ethereum-types/std",
	"evm/std",
	"evm-runtime/std",
	"sp-runtime-interface/std",
	"evm-gasometer/std",
]
