[package]
name = "evm-tracing-events"
version = '0.1.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]

codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["full"] }
ethereum = { version = "0.12", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.13.1", default-features = false, features = ["rlp","codec", "scale-info"] }

evm = { version = "0.35.0", default-features = false, features = ["with-codec"] }
evm-runtime = { version = "0.35.0", default-features = false }
evm-gasometer = { version = "0.35.0", default-features = false, features = ["tracing"]}
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
primitive-types = { version = "0.11.1", features = ["scale-info"] }
environmental = { version = "1.1.3", default-features = false }

[features]
default = ["std"]
evm-tracing = ["evm/tracing", "evm-runtime/tracing", "evm-gasometer/tracing"]
std = [
	"codec/std",
	"environmental/std",
	"ethereum/std",
	"ethereum-types/std",
	"evm/std",
	"evm-runtime/std",
	"sp-runtime-interface/std",
	"evm-gasometer/std",
]
