[package]
name = "edgeware-rpc"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "14.0.3"
sc-client-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
pallet-contracts-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
pallet-transaction-payment-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
substrate-frame-rpc-system = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-transaction-pool = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sc-keystore = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-consensus = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-blockchain = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sc-finality-grandpa = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sc-finality-grandpa-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sc-rpc-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
sp-block-builder = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-merge-upstream" }
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }