[package]
name = "edgeware-rpc"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
sc-client-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sp-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
pallet-contracts-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
pallet-transaction-payment-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
substrate-frame-rpc-system = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sp-transaction-pool = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sc-keystore = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sp-consensus = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sp-blockchain = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sc-finality-grandpa = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }
sc-finality-grandpa-rpc = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }

edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }