[package]
name = "edgeware-rpc"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
jsonrpc-core = "14.0.3"
sc-rpc = { path = "../../vendor/frontier/vendor/substrate/client/rpc" }
sc-consensus-manual-seal = { path = "../../vendor/frontier/vendor/substrate/client/consensus/manual-seal" }
sc-client-api = { path = "../../vendor/frontier/vendor/substrate/client/api" }
sp-api = { path = "../../vendor/frontier/vendor/substrate/primitives/api" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
pallet-transaction-payment-rpc = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment/rpc" }
substrate-frame-rpc-system = { path = "../../vendor/frontier/vendor/substrate/utils/frame/rpc/system" }
sp-transaction-pool = { path = "../../vendor/frontier/vendor/substrate/primitives/transaction-pool" }
sc-keystore = { path = "../../vendor/frontier/vendor/substrate/client/keystore" }
sp-consensus = { path = "../../vendor/frontier/vendor/substrate/primitives/consensus/common" }
sp-blockchain = { path = "../../vendor/frontier/vendor/substrate/primitives/blockchain" }
sc-finality-grandpa = { path = "../../vendor/frontier/vendor/substrate/client/finality-grandpa" }
sc-finality-grandpa-rpc = { path = "../../vendor/frontier/vendor/substrate/client/finality-grandpa/rpc" }
sc-rpc-api = { path = "../../vendor/frontier/vendor/substrate/client/rpc-api" }
sp-block-builder = { path = "../../vendor/frontier/vendor/substrate/primitives/block-builder" }
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }