version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.4.0
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/edgeware

    steps:
      - checkout
      - run: sudo apt-get update
      - run: ~/edgeware/scripts/init.sh
      - run: cd ~/edgeware && git submodule update --init --recursive

      # module test cases
      - run: source ~/.cargo/env && cd ~/edgeware && ./scripts/test.sh

      # ts test cases
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: cd ~/edgeware/ts-tests/frontier-tester && yarn
      - run: cd ~/edgeware/ts-tests/frontier-tester && yarn test-ci
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
