[package]
name = "edgeware-rpc-core-types"
version = '0.1.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
ethereum-types = { version = "0.12.1", default-features = false, features = ["codec"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
