[package]
name = "edgeware-inspect"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = { git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
sc-client-api = { git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
sc-service = { default-features = false, git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
sp-blockchain = { git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
sp-core = { git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
sp-runtime = { git = "https://github.com/drewstone/substrate.git", branch = "drew.customup" }
structopt = "0.3.8"