[package]
name = "edgeware-runtime-interface"
version = "3.2.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware runtime interface helpers and functions"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-runtime = { version = "2.0.0" }
sp-runtime-interface = { version = "2.0.0" }
sp-runtime-interface-proc-macro = { version = "2.0.0" }
edgeware-primitives = { path = "../primitives" }

[features]
default = [ "std" ]
std = [
  "sp-runtime/std",
  "sp-runtime-interface/std",
]