[package]
name = "edgeware-rpc-core-trace"
version = '0.6.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
ethereum-types = { version = "0.12.1", default-features = false, features = ["codec"] }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = { version = "0.3.1", features = ["compat"] }
edgeware-client-evm-tracing = { path = "../../evm-tracing" }
edgeware-rpc-core-types = { path = "../types" }