[package]
name = "edgeware-rpc-txpool"
version = '0.6.0'
authors = ['']
edition = '2021'
homepage = ''
license = 'GPL-3.0-only'
repository = ''

[dependencies]
rlp = "0.5"
sha3 = "0.9"
jsonrpc-core = "18.0.0"
ethereum-types = { version = "0.13.1", default-features = false, features = ["rlp","codec", "std"] }
ethereum = { version = "0.12", default-features = false, features = ["with-codec"] }
edgeware-rpc-core-txpool = { path = "../../rpc-core/txpool" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
serde = { version = "1.0", features = ["derive"] }

edgeware-rpc-primitives-txpool = { path = "../../../primitives/rpc/txpool" }
fc-rpc = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest", features = ["rpc_binary_search_estimate"] }
