[package]
name = "edgeware-rpc-txpool"
version = '0.6.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
rlp = "0.5"
sha3 = "0.9"
jsonrpc-core = "18.0.0"
ethereum-types = "0.12.0"
ethereum = { version = "0.10.0", default-features = false, features = ["with-codec"] }
edgeware-rpc-core-txpool = { path = "../../rpc-core/txpool" }
sp-runtime = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
sp-api = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
sp-io = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
sp-std = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
sp-blockchain = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
sc-transaction-pool = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218", features = ["test-helpers"] }
sc-transaction-pool-api = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
frame-system = { git = "https://github.com/remzrn/substrate", branch = "remz-substrate-upgrade-20211218" }
serde = { version = "1.0", features = ["derive"] }

edgeware-rpc-primitives-txpool = { path = "../../../primitives/rpc/txpool" }
fc-rpc = { git = "https://github.com/remzrn/frontier", branch = "remz-substrate-upgrade-20211218", features = ["rpc_binary_search_estimate"] }
