[package]
name = "edgeware-rpc-trace"
version = '0.6.0'
authors = ['PureStake']
edition = '2021'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
# Utils
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9"
ethereum-types = { version = "0.12.1", default-features = false, features = ["codec"]}
ethereum = { version = "0.11.1", features = ["with-codec"] }

# Async and logs
tokio = { version = "1.12.0", features = ["time", "sync"] }
futures = { version = "0.3" }
tracing = "0.1.25"

# Primitives
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
fp-rpc = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
edgeware-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }

# Client and RPC
jsonrpc-core = "18.0.0"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
fc-rpc = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest", features = ["rpc_binary_search_estimate"] }
fc-consensus = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
fc-rpc-core = { git = "https://github.com/edgeware-network/frontier", branch = "erup-5-latest" }
edgeware-rpc-core-trace = { path = "../../rpc-core/trace" }
edgeware-rpc-core-types = { path = "../../rpc-core/types" }
edgeware-client-evm-tracing = { path = "../../evm-tracing" }
