[package]
name = "edgeware-executor"
version = "1.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
trie-root = "0.14.0"
parity-codec = "4.1.1"
runtime_io = { package = "sr-io", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
substrate-executor = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
primitives = { package = "substrate-primitives", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
trie = { package = "substrate-trie", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
keyring = { package = "substrate-keyring", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
runtime_support = { package = "srml-support", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
balances = { package = "srml-balances", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
session = { package = "srml-session", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
staking = { package = "srml-staking", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
system = { package = "srml-system", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
timestamp = { package = "srml-timestamp", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
treasury = { package = "srml-treasury", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
contracts = { package = "srml-contracts", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
grandpa = { package = "srml-grandpa", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
indices = { package = "srml-indices", git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0" }
wabt = "~0.7.4"

[features]
benchmarks = []