[package]
name = "edgeware-executor"
version = "3.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trie-root = "0.16.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-io = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
sp-state-machine = { version = "0.8.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
sc-executor = { version = "0.8.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
sp-core = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
sp-trie = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
frame-benchmarking = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }

edgeware-primitives = { version = "3.1.0", path = "../primitives" }
edgeware-runtime = { version = "3.1.0", path = "../runtime" }
edgeware-runtime-interface = { version = "3.1.0", path = "../runtime-interface" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
sp-runtime = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
frame-support = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-balances = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-transaction-payment = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-session = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
frame-system = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-timestamp = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-treasury = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-grandpa = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
pallet-indices = { version = "2.0.0", git = "https://github.com/hicommonwealth/substrate.git", branch = "master" }
wabt = "0.10.0"
criterion = "0.3.0"

edgeware-testing = { version = "3.1.0", path = "../testing" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
