[package]
name = "edgeware-executor"
version = "0.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
edition = "2018"

[dependencies]
trie-root = "0.16.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-io = { version = "2.0.0"}
sp-state-machine = { version = "0.8.0"}
sc-executor = { version = "0.8.0"}
sp-core = { version = "2.0.0"}
sp-trie = { version = "2.0.0"}
frame-benchmarking = { version = "2.0.0"}

edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
edgeware-runtime-interface = { path = "../runtime-interface" }

[dev-dependencies]
sp-runtime = { version = "2.0.0"}
frame-support = { version = "2.0.0"}
pallet-balances = { version = "2.0.0"}
pallet-transaction-payment = { version = "2.0.0"}
pallet-session = { version = "2.0.0"}
frame-system = { version = "2.0.0"}
pallet-timestamp = { version = "2.0.0"}
pallet-treasury = { version = "2.0.0"}
pallet-grandpa = { version = "2.0.0"}
pallet-indices = { version = "2.0.0"}
wabt = "0.10.0"
criterion = "0.3.0"

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
